# Generated by Django 4.2.5 on 2023-09-28 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BajarApp', '0002_user_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(related_name='products', to='BajarApp.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_des',
            field=models.TextField(blank=True, default='', max_length=350, null=True),
        ),
    ]
