# Generated by Django 4.2.5 on 2023-09-28 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BajarApp', '0003_remove_product_category_product_categories_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='categories',
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BajarApp.category')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BajarApp.product')),
            ],
        ),
    ]
