# Generated by Django 4.2.5 on 2023-09-28 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BajarApp', '0004_remove_product_categories_productcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='BajarApp.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_des',
            field=models.TextField(blank=True, default='', max_length=300, null=True),
        ),
        migrations.DeleteModel(
            name='ProductCategory',
        ),
    ]
