# Generated by Django 4.2.5 on 2023-09-28 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BajarApp', '0006_rename_contuct_nuber_user_client_contuct_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_client',
            old_name='contuct_number',
            new_name='contact_number',
        ),
    ]
